#!/bin/bash

echo "Welcome $USER on $HOSTNAME"
echo ==================================================

FREE_RAM=$(free -m | grep 'Mem' | awk '{print $4}')
LOAD=`uptime | awk '{print $9}'`
ROOT_FREE=$(df -h | grep '/dev/sda1' | awk '{print $4}')

echo ==================================================
echo "Available free RAM size is $FREE_RAM MB"
echo ==================================================
echo "Current load average is : $LOAD"
echo ==================================================
echo "Free root partition size is : $ROOT_FREE"
