#!/bin/bash

read -p "Please enter a number : " NUM
echo

if [ $NUM -gt 100 ]
then
	echo "Entered in IF block"
	sleep 2
	echo "Your number is greater than 100"
	echo
	
	date
else
	echo "You have entered less than 100"
fi

echo "Script execution completed successfully."	
