#!/bin/bash

echo =================================================
date

#ls /var/run/httpd/httpd.pid &> /dev/null

	if [ -f /var/run/httpd/httpd.pid ]
	then
		echo "HTTPD Process is running"
	else
		echo "HTTPD Process is not running"
		echo "Starting the process"
		systemctl start httpd

	if [ $? -eq 0 ]
	then
		echo "Process started successfully"
	else
		echo "Process starting failed. Please contact the admin"
    fi
fi

echo ================================================
