#!/bin/bash

echo 'Enter your skills:'
read skill

echo "Your $skill skills is in high demand now."

read -p 'Username : ' USR
read -sp 'Password :' PASS

echo

echo "Login Successfull: Welcome $USR "
